cpo_monitor:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "db.ollmapfzhkdwuelpkzhd.supabase.co"   # replace with your Supabase host
      user: postgres
      password: "{{ env_var('DBT_PASSWORD') }}"   # set DBT_PASSWORD in your shell or .env
      port: 5432
      dbname: postgres
      schema: mart       # dbt writes mart models here by default
      threads: 4
      keepalives_idle: 0

    prod:
      type: postgres
      host: "db.ollmapfzhkdwuelpkzhd.supabase.co"
      user: postgres
      password: "{{ env_var('DBT_PASSWORD') }}"
      port: 5432
      dbname: postgres
      schema: mart
      threads: 4
      keepalives_idle: 0